export const SEARCH_GEOCODE_REQUESTED = "maps/SEARCH_GEOCODE_REQUESTED";
export const SEARCH_GEOCODE_FULFILLED = "maps/SEARCH_GEOCODE_FULFILLED";
export const SEARCH_GEOCODE_REJECTED = "maps/SEARCH_GEOCODE_REJECTED";