export const LIST_CATEGORIES_REQUESTED = "categories/LIST_CATEGORIES_REQUESTED";
export const LIST_CATEGORIES_FULFILLED = "categories/LIST_CATEGORIES_FULFILLED";
export const LIST_CATEGORIES_REJECTED = "categories/LIST_CATEGORIES_REJECTED";