export const SEARCH_PRODUCTS_REQUESTED = "products/SEARCH_PRODUCTS_REQUESTED";
export const SEARCH_PRODUCTS_FULFILLED = "products/SEARCH_PRODUCTS_FULFILLED";
export const SEARCH_PRODUCTS_REJECTED = "products/SEARCH_GEOCODE_REJECTED";