export const SEARCH_POC_REQUESTED = "products/SEARCH_POC_REQUESTED";
export const SEARCH_POC_FULFILLED = "products/SEARCH_POC_FULFILLED";
export const SEARCH_POC_REJECTED = "products/SEARCH_POC_REJECTED";

export const SEARCH_PRODUCTS_REQUESTED = "products/SEARCH_PRODUCTS_REQUESTED";
export const SEARCH_PRODUCTS_FULFILLED = "products/SEARCH_PRODUCTS_FULFILLED";
export const SEARCH_PRODUCTS_REJECTED = "products/SEARCH_PRODUCTS_REJECTED";